packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
catalog:
  {
    "@tanstack/react-query": "5.83.0",
    "@types/react": "19.1.8",
    "@types/react-dom": "19.1.6",
    "client-only": "0.0.1",
    "eslint": "9.30.1",
    "geist": "1.4.2",
    "lucide-react": "0.525.0",
    "nanoid": "5.1.6",
    "prettier": "3.6.2",
    "react": "19.1.0",
    "react-dom": "19.1.0",
    "server-only": "0.0.1",
    "tailwindcss": "4.1.11",
    "typescript": "5.8.3",
    "zod": "4.0.10",
  }
